In [1]:
import pandas as pd

df = pd.read_csv('sub_components2025_2026.csv')

In [2]:
#Check data frame
df.info()
print(df.describe())
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 11300 entries, 0 to 11299
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DATE                11300 non-null  str
 1   ITEM                11300 non-null  str
 2   NAME                11300 non-null  str
 3   SPEC                11300 non-null  str
 4   DRAWING             9780 non-null   str
 5   AC_CODE             11300 non-null  str
 6   WC_CODE             11260 non-null  str
 7   LOC                 11300 non-null  str
 8   DEPT                11300 non-null  int64
 9   VD_CODE             11300 non-null  str
 10  VD_NAME             11300 non-null  str
 11  UP                  11299 non-null  float64
 12  CUR                 11300 non-null  str
 13  PURLT               11300 non-null  int64
 14  ORDER_BAL           11300 non-null  int64
 15  SAFETY_STOCK        11300 non-null  int64
 16  ITEM_TYPE           11300 non-null  str
 17  UNIT                11300 non-null  str
 18  BEGIN_QTY           11300 non-null  int64
 19  RECEIVE_QTY         11300 non-null  int64
 20  ISSUE_QTY           11300 non-null  int64
 21  STOCK_QTY           11300 non-null  int64
 22  LAST_ISSUED_DATE    10180 non-null  str
 23  LAST_STOCK_IN_DATE  11300 non-null  str
dtypes: float64(1), int64(8), str(15)
memory usage: 2.1 MB
          DEPT            UP    PURLT     ORDER_BAL  SAFETY_STOCK  \
count  11300.0  11299.000000  11300.0  1.130000e+04  1.130000e+04
mean      90.0    233.339264      0.0  4.352530e+05  3.047221e+04
std        0.0   1244.844040      0.0  1.595628e+06  1.519799e+05
min       90.0      0.000000      0.0  0.000000e+00  0.000000e+00
25%       90.0      0.000000      0.0  0.000000e+00  0.000000e+00
50%       90.0      0.840000      0.0  0.000000e+00  0.000000e+00
75%       90.0      4.321353      0.0  8.000000e+04  8.400000e+02
max       90.0  12817.473540      0.0  1.719450e+07  3.000000e+06

          BEGIN_QTY   RECEIVE_QTY     ISSUE_QTY     STOCK_QTY
count  1.130000e+04  1.130000e+04  1.130000e+04  1.130000e+04
mean   1.271193e+05  2.783528e+05  2.793130e+05  1.261591e+05
std    3.947128e+05  1.047527e+06  1.042184e+06  3.873267e+05
min    0.000000e+00 -2.839680e+05 -1.232000e+05  0.000000e+00
25%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
50%    8.555000e+02  0.000000e+00  8.000000e+00  8.550000e+02
75%    7.810000e+04  4.562050e+04  5.484975e+04  8.176050e+04
max    7.164960e+06  1.633984e+07  1.662222e+07  7.164960e+06

,DATE,ITEM,NAME,SPEC,DRAWING,AC_CODE,WC_CODE,LOC,DEPT,VD_CODE,...,ORDER_BAL,SAFETY_STOCK,ITEM_TYPE,UNIT,BEGIN_QTY,RECEIVE_QTY,ISSUE_QTY,STOCK_QTY,LAST_ISSUED_DATE,LAST_STOCK_IN_DATE
0,1/1/2025,SKU-0001,STEEL BAR,STE-001,BP-2012D S,4520AA,TN29,3,90,NIP262,...,14651,500,P,KGS,0,0,0,0,8/6/2026,28/8/2026
1,1/1/2025,SKU-0002,STEEL BAR,STE-004,BP-2012D S,4520AA,TN29,3,90,NIP262,...,0,500,P,KGS,1519,14940,12490,3969,3/7/2025,18/7/2025
2,1/1/2025,SKU-0003,STEEL BAR,STE-003,BP-2012D S,4520AA,TN29,3,90,NIP262,...,15078,500,P,KGS,0,0,0,0,5/8/2026,31/8/2026
3,1/1/2025,SKU-0004,STEEL BAR,STE-004,BP-2012D S,4520AA,TN29,3,90,NIP262,...,0,0,P,KGS,0,0,0,0,6/6/2026,22/5/2026
4,1/1/2025,SKU-0005,STEEL BAR,STE-005,BP-2012O,4520AA,TN29,3,90,NIP262,...,0,0,P,KGS,0,0,0,0,11/5/2025,25/4/2025

In [3]:
#Check Duplicated Value
print('--------------Check Duplicated Values----------------')
print(df.duplicated().sum())

--------------Check Duplicated Values----------------
0

In [4]:
# Drop unnecessary columns
df = df.drop(columns=['DEPT','DRAWING','PURLT','SAFETY_STOCK','ITEM_TYPE'])
df.head()

,DATE,ITEM,NAME,SPEC,AC_CODE,WC_CODE,LOC,VD_CODE,VD_NAME,UP,CUR,ORDER_BAL,UNIT,BEGIN_QTY,RECEIVE_QTY,ISSUE_QTY,STOCK_QTY,LAST_ISSUED_DATE,LAST_STOCK_IN_DATE
0,1/1/2025,SKU-0001,STEEL BAR,STE-001,4520AA,TN29,3,NIP262,Nippon Precision Bar,NaN,BT,14651,KGS,0,0,0,0,8/6/2026,28/8/2026
1,1/1/2025,SKU-0002,STEEL BAR,STE-004,4520AA,TN29,3,NIP262,Nippon Precision Bar,88.150766,BT,0,KGS,1519,14940,12490,3969,3/7/2025,18/7/2025
2,1/1/2025,SKU-0003,STEEL BAR,STE-003,4520AA,TN29,3,NIP262,Nippon Precision Bar,0.000000,BT,15078,KGS,0,0,0,0,5/8/2026,31/8/2026
3,1/1/2025,SKU-0004,STEEL BAR,STE-004,4520AA,TN29,3,NIP262,Nippon Precision Bar,0.000000,BT,0,KGS,0,0,0,0,6/6/2026,22/5/2026
4,1/1/2025,SKU-0005,STEEL BAR,STE-005,4520AA,TN29,3,NIP262,Nippon Precision Bar,0.000000,BT,0,KGS,0,0,0,0,11/5/2025,25/4/2025

In [5]:
# Change Data Type
date_cols = ['DATE', 'LAST_ISSUED_DATE', 'LAST_STOCK_IN_DATE']

for col in date_cols:
    df[col] = pd.to_datetime(df[col], format='%d/%m/%Y', errors='coerce')

qty_amount_cols = ['BEGIN_QTY','RECEIVE_QTY','ISSUE_QTY','STOCK_QTY']

df[qty_amount_cols] = df[qty_amount_cols].astype('int64')
df.dtypes

DATE                  datetime64[us]
ITEM                             str
NAME                             str
SPEC                             str
AC_CODE                          str
WC_CODE                          str
LOC                              str
VD_CODE                          str
VD_NAME                          str
UP                           float64
CUR                              str
ORDER_BAL                      int64
UNIT                             str
BEGIN_QTY                      int64
RECEIVE_QTY                    int64
ISSUE_QTY                      int64
STOCK_QTY                      int64
LAST_ISSUED_DATE      datetime64[us]
LAST_STOCK_IN_DATE    datetime64[us]
dtype: object

In [6]:
#Check Null Values
print('--------------Check Null Values----------------')
print(df.isnull().sum())
# Fill null values
df['WC_CODE'] = df['WC_CODE'].fillna('Unknown')
df['UP'] = df['UP'].fillna(df['UP'].median())
df['LAST_ISSUED_DATE'] = df['LAST_ISSUED_DATE'].fillna(df['LAST_ISSUED_DATE'].mode()[0])
print('--------------Null Values After Filling----------------')
print(df.isnull().sum())

--------------Check Null Values----------------
DATE                     0
ITEM                     0
NAME                     0
SPEC                     0
AC_CODE                  0
WC_CODE                 40
LOC                      0
VD_CODE                  0
VD_NAME                  0
UP                       1
CUR                      0
ORDER_BAL                0
UNIT                     0
BEGIN_QTY                0
RECEIVE_QTY              0
ISSUE_QTY                0
STOCK_QTY                0
LAST_ISSUED_DATE      1120
LAST_STOCK_IN_DATE       0
dtype: int64
--------------Null Values After Filling----------------
DATE                  0
ITEM                  0
NAME                  0
SPEC                  0
AC_CODE               0
WC_CODE               0
LOC                   0
VD_CODE               0
VD_NAME               0
UP                    0
CUR                   0
ORDER_BAL             0
UNIT                  0
BEGIN_QTY             0
RECEIVE_QTY           0
ISSUE_QTY             0
STOCK_QTY             0
LAST_ISSUED_DATE      0
LAST_STOCK_IN_DATE    0
dtype: int64

In [7]:
# Check data frame after cleaning
print('--------------Data Frame After Cleaning----------------')
print(df.info())
display(df.sample(10))

--------------Data Frame After Cleaning----------------
<class 'pandas.DataFrame'>
RangeIndex: 11300 entries, 0 to 11299
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DATE                11300 non-null  datetime64[us]
 1   ITEM                11300 non-null  str
 2   NAME                11300 non-null  str
 3   SPEC                11300 non-null  str
 4   AC_CODE             11300 non-null  str
 5   WC_CODE             11300 non-null  str
 6   LOC                 11300 non-null  str
 7   VD_CODE             11300 non-null  str
 8   VD_NAME             11300 non-null  str
 9   UP                  11300 non-null  float64
 10  CUR                 11300 non-null  str
 11  ORDER_BAL           11300 non-null  int64
 12  UNIT                11300 non-null  str
 13  BEGIN_QTY           11300 non-null  int64
 14  RECEIVE_QTY         11300 non-null  int64
 15  ISSUE_QTY           11300 non-null  int64
 16  STOCK_QTY           11300 non-null  int64
 17  LAST_ISSUED_DATE    11300 non-null  datetime64[us]
 18  LAST_STOCK_IN_DATE  11300 non-null  datetime64[us]
dtypes: datetime64[us](3), float64(1), int64(5), str(10)
memory usage: 1.6 MB
None

,DATE,ITEM,NAME,SPEC,AC_CODE,WC_CODE,LOC,VD_CODE,VD_NAME,UP,CUR,ORDER_BAL,UNIT,BEGIN_QTY,RECEIVE_QTY,ISSUE_QTY,STOCK_QTY,LAST_ISSUED_DATE,LAST_STOCK_IN_DATE
6549,2025-12-01,SKU-0335,RUBBER SEAL,RUB-00335,4520DB,GS99,4,ELA865,ElastoSeal Tech Solutions,0.941250,BT,96000,PCS,69740,0,20240,49500,2026-08-05,2026-04-09
8921,2026-04-01,SKU-0447,STOP RING,STO-00447,4520FA,GS99,4,PRI894,Prime Ring & Retainer Industrie,1.011000,BT,0,PCS,13024,0,0,13024,2026-08-05,2024-10-28
2045,2025-04-01,SKU-0351,RUBBER SEAL,RUB-00351,4520DB,GS99,4,ELA865,ElastoSeal Tech Solutions,3.868320,BT,749000,PCS,639320,302720,183700,758340,2026-08-05,2026-08-11
2389,2025-05-01,SKU-0130,BALL,BAL-00130,4520BD,AS99,I2,MIN471,Minebea HQ,223.066796,BT,1350,KPS,1968,0,621,1346,2026-08-24,2026-08-19
1501,2025-03-01,SKU-0372,RUBBER SEAL,RUB-00372,4520DB,GS99,4,ELA865,ElastoSeal Tech Solutions,0.969174,BT,1633030,PCS,1021442,821146,928541,914047,2026-08-31,2026-08-31
10680,2026-07-01,SKU-0511,INNER RING,INN-00511,4520PA,SF29,4,MIN471,Minebea HQ,0.000000,BT,0,PCS,0,0,0,0,2023-09-28,2026-03-26
8549,2026-04-01,SKU-0075,CERAMIC BALL,CER-0075,4520BL,AS99,B2,MIN471,Minebea HQ,6873.770755,BT,0,KPS,14,0,0,14,2026-08-05,2020-11-23
777,2025-02-01,SKU-0213,RETAINER,RET-00213,4520CA,AS99,4S,KOY613,Koyo Precision Stamping Works,0.333900,BT,896000,SET,316800,749760,696960,369600,2026-08-30,2026-08-27
10157,2026-06-01,SKU-0553,INNER RING,INN-00553,4520PA,TN29,4,MIN471,Minebea HQ,0.000000,BT,0,PCS,0,0,0,0,2026-08-05,2026-08-31
3808,2025-07-01,SKU-0419,RUBBER SEAL,RUB-00419,4520DS,GS99,4,MIN471,Minebea HQ,0.000000,BT,0,PCS,0,0,0,0,2025-06-19,2025-06-25

In [8]:
#Insert Columns
df['STOCK_AGE'] = (pd.Timestamp.now() - df['LAST_STOCK_IN_DATE']).dt.days // 30
df['GROUP_AGE'] = pd.cut(df['STOCK_AGE'], bins=[0, 3, 6, 12, 24, float('inf')], labels=['0-3 months', '3-6 months', '6-12 months', '12-24 months', '24+ months'])
df['GROUP_AGE'] = df['GROUP_AGE'].astype('category').fillna('0-3 months')

print('--------------Data Frame After Adding Columns----------------')
print(df.info())
display(df[['LAST_STOCK_IN_DATE','STOCK_AGE','GROUP_AGE']].sample(10))

--------------Data Frame After Adding Columns----------------
<class 'pandas.DataFrame'>
RangeIndex: 11300 entries, 0 to 11299
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DATE                11300 non-null  datetime64[us]
 1   ITEM                11300 non-null  str
 2   NAME                11300 non-null  str
 3   SPEC                11300 non-null  str
 4   AC_CODE             11300 non-null  str
 5   WC_CODE             11300 non-null  str
 6   LOC                 11300 non-null  str
 7   VD_CODE             11300 non-null  str
 8   VD_NAME             11300 non-null  str
 9   UP                  11300 non-null  float64
 10  CUR                 11300 non-null  str
 11  ORDER_BAL           11300 non-null  int64
 12  UNIT                11300 non-null  str
 13  BEGIN_QTY           11300 non-null  int64
 14  RECEIVE_QTY         11300 non-null  int64
 15  ISSUE_QTY           11300 non-null  int64
 16  STOCK_QTY           11300 non-null  int64
 17  LAST_ISSUED_DATE    11300 non-null  datetime64[us]
 18  LAST_STOCK_IN_DATE  11300 non-null  datetime64[us]
 19  STOCK_AGE           11300 non-null  int64
 20  GROUP_AGE           11300 non-null  category
dtypes: category(1), datetime64[us](3), float64(1), int64(6), str(10)
memory usage: 1.7 MB
None

      LAST_STOCK_IN_DATE  STOCK_AGE    GROUP_AGE
2694          2026-08-13          0   0-3 months
7658          2025-10-01         11  6-12 months
6644          2025-10-09         10  6-12 months
3831          2026-08-03          1   0-3 months
7725          2026-07-22          1   0-3 months
3279          2023-07-13         38   24+ months
815           2026-08-28          0   0-3 months
10934         2026-08-25          0   0-3 months
7470          2026-07-21          1   0-3 months
3668          2026-06-24          2   0-3 months

In [9]:
df.to_csv('sub_components2025_2026_cleaned.csv', index=False)