In [48]:
import pandas as pd

df = pd.read_csv('sub_components2025_2026.csv')

In [49]:
#Check data frame
df.info()
print(df.describe())
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 11300 entries, 0 to 11299
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DATE                11300 non-null  str
 1   ITEM                11300 non-null  str
 2   NAME                11300 non-null  str
 3   SPEC                11300 non-null  str
 4   DRAWING             9780 non-null   str
 5   AC_CODE             11300 non-null  str
 6   WC_CODE             11260 non-null  str
 7   LOC                 11300 non-null  str
 8   DEPT                11300 non-null  int64
 9   VD_CODE             11300 non-null  str
 10  VD_NAME             11300 non-null  str
 11  UP                  11299 non-null  float64
 12  CUR                 11300 non-null  str
 13  PURLT               11300 non-null  int64
 14  ORDER_BAL           11300 non-null  int64
 15  SAFETY_STOCK        11300 non-null  int64
 16  ITEM_TYPE           11300 non-null  str
 17  UNIT                11300 non-null  str
 18  BEGIN_QTY           11300 non-null  float64
 19  RECEIVE_QTY         11300 non-null  float64
 20  ISSUE_QTY           11300 non-null  float64
 21  STOCK_QTY           11300 non-null  float64
 22  BEGIN_AMOUNT        11300 non-null  float64
 23  RECEIVE_AMOUNT      11300 non-null  float64
 24  ISSUE_AMOUNT        11300 non-null  float64
 25  STOCK_AMOUNT        11300 non-null  float64
 26  LAST_ISSUED_DATE    10180 non-null  str
 27  LAST_STOCK_IN_DATE  11300 non-null  str
dtypes: float64(9), int64(4), str(15)
memory usage: 2.4 MB
          DEPT            UP    PURLT     ORDER_BAL  SAFETY_STOCK  \
count  11300.0  11299.000000  11300.0  1.130000e+04  1.130000e+04
mean      90.0    233.339264      0.0  4.352530e+05  3.047221e+04
std        0.0   1244.844040      0.0  1.595628e+06  1.519799e+05
min       90.0      0.000000      0.0  0.000000e+00  0.000000e+00
25%       90.0      0.000000      0.0  0.000000e+00  0.000000e+00
50%       90.0      0.840000      0.0  0.000000e+00  0.000000e+00
75%       90.0      4.321353      0.0  8.000000e+04  8.400000e+02
max       90.0  12817.473540      0.0  1.719450e+07  3.000000e+06

          BEGIN_QTY   RECEIVE_QTY     ISSUE_QTY     STOCK_QTY  BEGIN_AMOUNT  \
count  1.130000e+04  1.130000e+04  1.130000e+04  1.130000e+04  1.130000e+04
mean   1.444537e+05  3.163100e+05  3.174011e+05  1.433626e+05  1.572483e+05
std    4.485373e+05  1.190372e+06  1.184300e+06  4.401440e+05  4.542108e+05
min    0.000000e+00 -3.226910e+05 -1.400000e+05  0.000000e+00  0.000000e+00
25%    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
50%    9.723000e+02  0.000000e+00  9.200000e+00  9.720000e+02  1.775690e+04
75%    8.875000e+04  5.184175e+04  6.232957e+04  9.291000e+04  1.121909e+05
max    8.142000e+06  1.856800e+07  1.888889e+07  8.142000e+06  7.161882e+06

       RECEIVE_AMOUNT  ISSUE_AMOUNT  STOCK_AMOUNT
count    1.130000e+04  1.130000e+04  1.130000e+04
mean     2.952454e+05  2.967552e+05  1.557385e+05
std      1.577454e+06  1.576909e+06  4.480312e+05
min     -2.897384e+05 -1.522257e+05  0.000000e+00
25%      0.000000e+00  0.000000e+00  0.000000e+00
50%      0.000000e+00  2.691600e+02  1.812917e+04
75%      1.495734e+05  1.577886e+05  1.131921e+05
max      3.795786e+07  3.720916e+07  7.161882e+06

,DATE,ITEM,NAME,SPEC,DRAWING,AC_CODE,WC_CODE,LOC,DEPT,VD_CODE,...,BEGIN_QTY,RECEIVE_QTY,ISSUE_QTY,STOCK_QTY,BEGIN_AMOUNT,RECEIVE_AMOUNT,ISSUE_AMOUNT,STOCK_AMOUNT,LAST_ISSUED_DATE,LAST_STOCK_IN_DATE
0,1/1/2025,SKU-0001,STEEL BAR,STE-001,BP-2012D S,4520AA,TN29,3,90,NIP262,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,8/6/2026,28/8/2026
1,1/1/2025,SKU-0002,STEEL BAR,STE-004,BP-2012D S,4520AA,TN29,3,90,NIP262,...,1726.0,16977.0,14193.0,4510.0,102651.26,992645.19,831179.12,264117.33,3/7/2025,18/7/2025
2,1/1/2025,SKU-0003,STEEL BAR,STE-003,BP-2012D S,4520AA,TN29,3,90,NIP262,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,5/8/2026,31/8/2026
3,1/1/2025,SKU-0004,STEEL BAR,STE-004,BP-2012D S,4520AA,TN29,3,90,NIP262,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,6/6/2026,22/5/2026
4,1/1/2025,SKU-0005,STEEL BAR,STE-005,BP-2012O,4520AA,TN29,3,90,NIP262,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,11/5/2025,25/4/2025

In [50]:
#Check Duplicated Value
print('--------------Check Duplicated Values----------------')
print(df.duplicated().sum())

--------------Check Duplicated Values----------------
0

In [51]:
# Drop unnecessary columns
df = df.drop(columns=['DEPT','DRAWING','PURLT','SAFETY_STOCK','ITEM_TYPE'])
df.head()

,DATE,ITEM,NAME,SPEC,AC_CODE,WC_CODE,LOC,VD_CODE,VD_NAME,UP,...,BEGIN_QTY,RECEIVE_QTY,ISSUE_QTY,STOCK_QTY,BEGIN_AMOUNT,RECEIVE_AMOUNT,ISSUE_AMOUNT,STOCK_AMOUNT,LAST_ISSUED_DATE,LAST_STOCK_IN_DATE
0,1/1/2025,SKU-0001,STEEL BAR,STE-001,4520AA,TN29,3,NIP262,Nippon Precision Bar,NaN,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,8/6/2026,28/8/2026
1,1/1/2025,SKU-0002,STEEL BAR,STE-004,4520AA,TN29,3,NIP262,Nippon Precision Bar,88.150766,...,1726.0,16977.0,14193.0,4510.0,102651.26,992645.19,831179.12,264117.33,3/7/2025,18/7/2025
2,1/1/2025,SKU-0003,STEEL BAR,STE-003,4520AA,TN29,3,NIP262,Nippon Precision Bar,0.000000,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,5/8/2026,31/8/2026
3,1/1/2025,SKU-0004,STEEL BAR,STE-004,4520AA,TN29,3,NIP262,Nippon Precision Bar,0.000000,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,6/6/2026,22/5/2026
4,1/1/2025,SKU-0005,STEEL BAR,STE-005,4520AA,TN29,3,NIP262,Nippon Precision Bar,0.000000,...,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,11/5/2025,25/4/2025

In [52]:
# Change Data Type
date_cols = ['DATE', 'LAST_ISSUED_DATE', 'LAST_STOCK_IN_DATE']

for col in date_cols:
    df[col] = pd.to_datetime(df[col], format='%d/%m/%Y', errors='coerce')

qty_amount_cols = ['BEGIN_QTY','RECEIVE_QTY','ISSUE_QTY','STOCK_QTY',
                    'BEGIN_AMOUNT','RECEIVE_AMOUNT','STOCK_AMOUNT','ISSUE_AMOUNT']

df[qty_amount_cols] = df[qty_amount_cols].astype('int64')
df.dtypes

DATE                  datetime64[us]
ITEM                             str
NAME                             str
SPEC                             str
AC_CODE                          str
WC_CODE                          str
LOC                              str
VD_CODE                          str
VD_NAME                          str
UP                           float64
CUR                              str
ORDER_BAL                      int64
UNIT                             str
BEGIN_QTY                      int64
RECEIVE_QTY                    int64
ISSUE_QTY                      int64
STOCK_QTY                      int64
BEGIN_AMOUNT                   int64
RECEIVE_AMOUNT                 int64
ISSUE_AMOUNT                   int64
STOCK_AMOUNT                   int64
LAST_ISSUED_DATE      datetime64[us]
LAST_STOCK_IN_DATE    datetime64[us]
dtype: object

In [53]:
#Check Null Values
print('--------------Check Null Values----------------')
print(df.isnull().sum())
# Fill null values
df['WC_CODE'] = df['WC_CODE'].fillna('Unknown')
df['UP'] = df['UP'].fillna(df['UP'].median())
df['LAST_ISSUED_DATE'] = df['LAST_ISSUED_DATE'].fillna(df['LAST_ISSUED_DATE'].mode()[0])
print('--------------Null Values After Filling----------------')
print(df.isnull().sum())

--------------Check Null Values----------------
DATE                     0
ITEM                     0
NAME                     0
SPEC                     0
AC_CODE                  0
WC_CODE                 40
LOC                      0
VD_CODE                  0
VD_NAME                  0
UP                       1
CUR                      0
ORDER_BAL                0
UNIT                     0
BEGIN_QTY                0
RECEIVE_QTY              0
ISSUE_QTY                0
STOCK_QTY                0
BEGIN_AMOUNT             0
RECEIVE_AMOUNT           0
ISSUE_AMOUNT             0
STOCK_AMOUNT             0
LAST_ISSUED_DATE      1120
LAST_STOCK_IN_DATE       0
dtype: int64
--------------Null Values After Filling----------------
DATE                  0
ITEM                  0
NAME                  0
SPEC                  0
AC_CODE               0
WC_CODE               0
LOC                   0
VD_CODE               0
VD_NAME               0
UP                    0
CUR                   0
ORDER_BAL             0
UNIT                  0
BEGIN_QTY             0
RECEIVE_QTY           0
ISSUE_QTY             0
STOCK_QTY             0
BEGIN_AMOUNT          0
RECEIVE_AMOUNT        0
ISSUE_AMOUNT          0
STOCK_AMOUNT          0
LAST_ISSUED_DATE      0
LAST_STOCK_IN_DATE    0
dtype: int64

In [54]:
# Check data frame after cleaning
print('--------------Data Frame After Cleaning----------------')
print(df.info())
display(df.sample(10))

--------------Data Frame After Cleaning----------------
<class 'pandas.DataFrame'>
RangeIndex: 11300 entries, 0 to 11299
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DATE                11300 non-null  datetime64[us]
 1   ITEM                11300 non-null  str
 2   NAME                11300 non-null  str
 3   SPEC                11300 non-null  str
 4   AC_CODE             11300 non-null  str
 5   WC_CODE             11300 non-null  str
 6   LOC                 11300 non-null  str
 7   VD_CODE             11300 non-null  str
 8   VD_NAME             11300 non-null  str
 9   UP                  11300 non-null  float64
 10  CUR                 11300 non-null  str
 11  ORDER_BAL           11300 non-null  int64
 12  UNIT                11300 non-null  str
 13  BEGIN_QTY           11300 non-null  int64
 14  RECEIVE_QTY         11300 non-null  int64
 15  ISSUE_QTY           11300 non-null  int64
 16  STOCK_QTY           11300 non-null  int64
 17  BEGIN_AMOUNT        11300 non-null  int64
 18  RECEIVE_AMOUNT      11300 non-null  int64
 19  ISSUE_AMOUNT        11300 non-null  int64
 20  STOCK_AMOUNT        11300 non-null  int64
 21  LAST_ISSUED_DATE    11300 non-null  datetime64[us]
 22  LAST_STOCK_IN_DATE  11300 non-null  datetime64[us]
dtypes: datetime64[us](3), float64(1), int64(9), str(10)
memory usage: 2.0 MB
None

,DATE,ITEM,NAME,SPEC,AC_CODE,WC_CODE,LOC,VD_CODE,VD_NAME,UP,...,BEGIN_QTY,RECEIVE_QTY,ISSUE_QTY,STOCK_QTY,BEGIN_AMOUNT,RECEIVE_AMOUNT,ISSUE_AMOUNT,STOCK_AMOUNT,LAST_ISSUED_DATE,LAST_STOCK_IN_DATE
1427,2025-03-01,SKU-0298,RUBBER SEAL,RUB-00298,4520DB,GS99,4,ELA865,ElastoSeal Tech Solutions,0.968655,...,207150,229625,113375,323400,134481,147539,73201,208819,2026-08-05,2026-08-17
7750,2026-02-01,SKU-0406,RUBBER SEAL,RUB-00406,4520DB,GS99,4,ELA865,ElastoSeal Tech Solutions,0.000000,...,0,0,0,0,0,0,0,0,2026-04-08,2026-03-09
2635,2025-05-01,SKU-0376,RUBBER SEAL,RUB-00376,4520DB,GS99,4,ELA865,ElastoSeal Tech Solutions,2.479928,...,414500,0,77250,337250,685268,0,127726,557541,2026-08-05,2025-07-22
11252,2026-08-01,SKU-0518,INNER RING,INN-00518,4520PA,SF29,4,MIN471,Minebea HQ,0.000000,...,0,0,0,0,0,0,0,0,2023-10-31,2026-02-27
8136,2026-03-01,SKU-0227,RETAINER,RET-00227,4520CE,Unknown,4,MIN471,Minebea HQ,0.000000,...,0,0,0,0,0,0,0,0,2025-09-08,2025-08-06
9733,2026-06-01,SKU-0129,BALL,BAL-00129,4520BC,AS99,M2,MIN471,Minebea HQ,216.384312,...,870,300,256,913,125117,43495,37022,131590,2026-08-24,2026-06-10
5840,2025-11-01,SKU-0191,RETAINER,RET-00191,4520CD,AS99,4,PRI894,Prime Ring & Retainer Industries,0.418301,...,893700,2300400,1512000,1682100,245052,648366,422935,470483,2026-08-05,2026-08-31
348,2025-01-01,SKU-0349,RUBBER SEAL,RUB-00349,4520DB,GS99,4,ELA865,ElastoSeal Tech Solutions,0.983794,...,20000,50000,16500,53500,13202,32656,10809,35049,2026-08-05,2025-09-18
5687,2025-11-01,SKU-0038,STEEL BAR,STE-0036,4520AA,TN29,3,NIP262,Nippon Precision Bar,0.000000,...,0,0,0,0,0,0,0,0,2026-08-05,2026-08-28
5699,2025-11-01,SKU-0050,STEEL PIPE,STE-0050,4520AF,TN19,3,SUM330,Sumitomo Metal Solutions,227.746361,...,507,0,0,507,76978,0,0,76978,2026-06-06,2025-01-03

In [55]:
#Insert Columns
df['STOCK_AGE'] = (pd.Timestamp.now() - df['LAST_STOCK_IN_DATE']).dt.days // 30
df['GROUP_AGE'] = pd.cut(df['STOCK_AGE'], bins=[0, 3, 6, 12, 24, float('inf')], labels=['0-3 months', '3-6 months', '6-12 months', '12-24 months', '24+ months'])
df['GROUP_AGE'] = df['GROUP_AGE'].astype('category').fillna('0-3 months')

print('--------------Data Frame After Adding Columns----------------')
print(df.info())
display(df[['LAST_STOCK_IN_DATE','STOCK_AGE','GROUP_AGE']].sample(10))

--------------Data Frame After Adding Columns----------------
<class 'pandas.DataFrame'>
RangeIndex: 11300 entries, 0 to 11299
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DATE                11300 non-null  datetime64[us]
 1   ITEM                11300 non-null  str
 2   NAME                11300 non-null  str
 3   SPEC                11300 non-null  str
 4   AC_CODE             11300 non-null  str
 5   WC_CODE             11300 non-null  str
 6   LOC                 11300 non-null  str
 7   VD_CODE             11300 non-null  str
 8   VD_NAME             11300 non-null  str
 9   UP                  11300 non-null  float64
 10  CUR                 11300 non-null  str
 11  ORDER_BAL           11300 non-null  int64
 12  UNIT                11300 non-null  str
 13  BEGIN_QTY           11300 non-null  int64
 14  RECEIVE_QTY         11300 non-null  int64
 15  ISSUE_QTY           11300 non-null  int64
 16  STOCK_QTY           11300 non-null  int64
 17  BEGIN_AMOUNT        11300 non-null  int64
 18  RECEIVE_AMOUNT      11300 non-null  int64
 19  ISSUE_AMOUNT        11300 non-null  int64
 20  STOCK_AMOUNT        11300 non-null  int64
 21  LAST_ISSUED_DATE    11300 non-null  datetime64[us]
 22  LAST_STOCK_IN_DATE  11300 non-null  datetime64[us]
 23  STOCK_AGE           11300 non-null  int64
 24  GROUP_AGE           11300 non-null  category
dtypes: category(1), datetime64[us](3), float64(1), int64(10), str(10)
memory usage: 2.1 MB
None

      LAST_STOCK_IN_DATE  STOCK_AGE     GROUP_AGE
105           2026-08-04          0    0-3 months
4543          2025-05-23         15  12-24 months
3210          2024-08-01         25    24+ months
969           2026-04-07          4    3-6 months
9158          2026-08-27          0    0-3 months
8207          2026-08-17          0    0-3 months
10721         2026-07-31          1    0-3 months
4607          2026-05-27          3    0-3 months
7549          2026-08-28          0    0-3 months
10774         2025-07-09         13  12-24 months

In [56]:
df.to_csv('sub_components2025_2026_cleaned.csv', index=False)