In [61]:
import pandas as pd

df = pd.read_csv('../Data/PO_Outgoing_List.csv')

print("\n ----------รายละเอียด----------")
print(df.info())
print("\n ----------จำนวนแถวและคอมลัมน์----------")
print(df.shape)
print("\n ----------จำนวนข้อมูลซ้ำ----------")
print(df.duplicated().sum())
print("\n ----------จำนวนข้อมูลว่าง----------")
print(df.isna().sum())
print("\n ----------ตัวอย่างข้อมูล----------")
display(df.sample(5))

 ----------รายละเอียด----------
<class 'pandas.DataFrame'>
RangeIndex: 22553 entries, 0 to 22552
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SECTION           22553 non-null  int64
 1   SENT_DATE         22553 non-null  str
 2   VENDOR            22553 non-null  int64
 3   PONO              22553 non-null  str
 4   ITEM_NO           10398 non-null  str
 5   ITEM_NAME         22553 non-null  str
 6   SPEC              22548 non-null  str
 7   DUEDATE           22553 non-null  str
 8   UNIT_PRICE        22553 non-null  float64
 9   ORDER_QTY         22553 non-null  float64
 10  ORDER_AMT         22553 non-null  float64
 11  BUYER_NAME        22553 non-null  str
 12  AUTHOLIZER_NAME   22553 non-null  str
 13  SENDING_DATETIME  22553 non-null  str
 14  Unnamed: 14       0 non-null      float64
dtypes: float64(4), int64(2), str(9)
memory usage: 2.6 MB
None

 ----------จำนวนแถวและคอมลัมน์----------
(22553, 15)

 ----------จำนวนข้อมูลซ้ำ----------
0

 ----------จำนวนข้อมูลว่าง----------
SECTION                 0
SENT_DATE               0
VENDOR                  0
PONO                    0
ITEM_NO             12155
ITEM_NAME               0
SPEC                    5
DUEDATE                 0
UNIT_PRICE              0
ORDER_QTY               0
ORDER_AMT               0
BUYER_NAME              0
AUTHOLIZER_NAME         0
SENDING_DATETIME        0
Unnamed: 14         22553
dtype: int64

 ----------ตัวอย่างข้อมูล----------

,SECTION,SENT_DATE,VENDOR,PONO,ITEM_NO,ITEM_NAME,SPEC,DUEDATE,UNIT_PRICE,ORDER_QTY,ORDER_AMT,BUYER_NAME,AUTHOLIZER_NAME,SENDING_DATETIME,Unnamed: 14
3585,7211,2026/02/18,2105697,TC29739,NHV-22005,ROLLER,PT37001-04-0230D,2026-03-04,10200.00,2.0,20400.0,MRS.KARNJANA GOGERD,MRS.KARNJANA GOGERD,2026-02-18-11.02.32,NaN
7840,7211,2026/04/01,2008058,STA8530,FY6310100,GREASE,LY631;HIGHSPEED L252 (1KG/CAN),2026-04-01,15500.00,2.0,31000.0,MRS.KARNJANA GOGERD,MRS.KARNJANA GOGERD,2026-04-01-13.21.39,NaN
21534,7211,2026/08/17,2008389,AA07197,NaN,CYLINDER HOLDER,PT37056-05-T5920,2026-08-17,650.00,2.0,1300.0,MRS.KARNJANA GOGERD,MRS.KARNJANA GOGERD,2026-08-17-09.47.45,NaN
14319,7211,2026/06/08,2008389,TC31051,NPT-57022,GREASE CHECK STATION WING,PT34064-126-2001 608,2026-06-08,350.00,2.0,700.0,MRS.KARNJANA GOGERD,MRS.KARNJANA GOGERD,2026-06-08-11.32.30,NaN
9900,7211,2026/04/27,2060495,STA9239,AJ158000SSM,STEEL COIL,SUJ-2MDSF-MTBL 15.8,2026-04-30,57.97,560300.0,32480591.0,MRS.KARNJANA GOGERD,MRS.KARNJANA GOGERD,2026-04-27-15.35.13,NaN

In [62]:
#แปลงชนิดข้อมูลคอมลัมน์ SECTION และ VENDOR เป็น string

df = df.astype({'SECTION':'str','VENDOR':'str'})
print("\n -----------รายละเอียด-----------")
print(df.info())

 -----------รายละเอียด-----------
<class 'pandas.DataFrame'>
RangeIndex: 22553 entries, 0 to 22552
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SECTION           22553 non-null  str
 1   SENT_DATE         22553 non-null  str
 2   VENDOR            22553 non-null  str
 3   PONO              22553 non-null  str
 4   ITEM_NO           10398 non-null  str
 5   ITEM_NAME         22553 non-null  str
 6   SPEC              22548 non-null  str
 7   DUEDATE           22553 non-null  str
 8   UNIT_PRICE        22553 non-null  float64
 9   ORDER_QTY         22553 non-null  float64
 10  ORDER_AMT         22553 non-null  float64
 11  BUYER_NAME        22553 non-null  str
 12  AUTHOLIZER_NAME   22553 non-null  str
 13  SENDING_DATETIME  22553 non-null  str
 14  Unnamed: 14       0 non-null      float64
dtypes: float64(4), str(11)
memory usage: 2.6 MB
None

In [63]:
#แปลงชนิดข้อมูลวันที่
df['SENT_DATE'] = pd.to_datetime(df['SENT_DATE'],errors='coerce')
df['DUEDATE'] = pd.to_datetime(df['DUEDATE'],errors='coerce')
df['SENDING_DATETIME'] = df['SENDING_DATETIME'].astype('str').str[:10]
df['SENDING_DATETIME'] = pd.to_datetime(df['SENDING_DATETIME'],errors='coerce')

print("\n ตรวจสอบข้อมูล")
print(df.info())
print('\n ตัวอย่างข้อมูล')
display(df.sample(5))

 ตรวจสอบข้อมูล
<class 'pandas.DataFrame'>
RangeIndex: 22553 entries, 0 to 22552
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SECTION           22553 non-null  str
 1   SENT_DATE         22553 non-null  datetime64[us]
 2   VENDOR            22553 non-null  str
 3   PONO              22553 non-null  str
 4   ITEM_NO           10398 non-null  str
 5   ITEM_NAME         22553 non-null  str
 6   SPEC              22548 non-null  str
 7   DUEDATE           22553 non-null  datetime64[us]
 8   UNIT_PRICE        22553 non-null  float64
 9   ORDER_QTY         22553 non-null  float64
 10  ORDER_AMT         22553 non-null  float64
 11  BUYER_NAME        22553 non-null  str
 12  AUTHOLIZER_NAME   22553 non-null  str
 13  SENDING_DATETIME  22553 non-null  datetime64[us]
 14  Unnamed: 14       0 non-null      float64
dtypes: datetime64[us](3), float64(4), str(8)
memory usage: 2.6 MB
None

 ตัวอย่างข้อมูล

,SECTION,SENT_DATE,VENDOR,PONO,ITEM_NO,ITEM_NAME,SPEC,DUEDATE,UNIT_PRICE,ORDER_QTY,ORDER_AMT,BUYER_NAME,AUTHOLIZER_NAME,SENDING_DATETIME,Unnamed: 14
7937,7211,2026-04-01,2105697,TC31227,CFT-02029R2,KO PIN-23,PT44189-56-0009-2001C(R3) 1-608,2026-05-04,150.00,17.0,2550.00,MS.PHUNCHALEE MEEPRADIT,MS.PHUNCHALEE MEEPRADIT,2026-04-01,NaN
6884,7211,2026-03-21,2002207,MSJ7502,SWN-01032,CAP SCREW,M8X20,2026-04-01,2.08,100.0,208.00,MS.PHUNCHALEE MEEPRADIT,MS.PHUNCHALEE MEEPRADIT,2026-03-21,NaN
8640,7211,2026-04-10,2008389,AA05015,NaN,CLAMP HOLDER B,PT47P04-01-0420,2026-06-10,300.00,1.0,300.00,MS.PHUNCHALEE MEEPRADIT,MS.PHUNCHALEE MEEPRADIT,2026-04-10,NaN
10988,7211,2026-05-06,2105697,TC31623,CFT-02030R2,KO PIN-1,PT44189-56-T0474-1001(R2) 1-608,2026-06-04,170.00,17.0,2890.00,MS.PHUNCHALEE MEEPRADIT,MS.PHUNCHALEE MEEPRADIT,2026-05-06,NaN
1778,7211,2026-01-27,2005607,MM05581,NaN,END CAP,HFCB6-3030-B,2026-02-04,63.53,8.0,508.24,MS.PHUNCHALEE MEEPRADIT,MS.PHUNCHALEE MEEPRADIT,2026-01-27,NaN

In [64]:
#ลบคอลัมน์ที่ไม่มีข้อิมูลเลย เติมข้อมูลในแถวว่าง
df = df.dropna(axis=1, how='all')
df = df.fillna({'ITEM_NO':'Unknown', 'SPEC':'Unknown'})

print('\nจำนวนข้อมูลว่าง')
print(df.isna().sum())
display(df.sample(5))

จำนวนข้อมูลว่าง
SECTION             0
SENT_DATE           0
VENDOR              0
PONO                0
ITEM_NO             0
ITEM_NAME           0
SPEC                0
DUEDATE             0
UNIT_PRICE          0
ORDER_QTY           0
ORDER_AMT           0
BUYER_NAME          0
AUTHOLIZER_NAME     0
SENDING_DATETIME    0
dtype: int64

,SECTION,SENT_DATE,VENDOR,PONO,ITEM_NO,ITEM_NAME,SPEC,DUEDATE,UNIT_PRICE,ORDER_QTY,ORDER_AMT,BUYER_NAME,AUTHOLIZER_NAME,SENDING_DATETIME
5604,7211,2026-03-09,2008375,TC30825,KA09701R,DRILL,SIZE:9.7 (COATING)2-6000 1910 2210,2026-03-05,45.8,12.0,549.6,MRS.KARNJANA GOGERD,MRS.KARNJANA GOGERD,2026-03-09
6129,7211,2026-03-16,2105697,FM60902,Unknown,VERTICAL TRANSFER SHAFT,PT37189-07-T1030,2026-04-22,4250.0,3.0,12750.0,MS.PHUNCHALEE MEEPRADIT,MS.PHUNCHALEE MEEPRADIT,2026-03-16
13757,7211,2026-06-05,2660073,MM06393,Unknown,CYLINDER BASE,PT37064-04-T6232,2026-06-16,950.0,2.0,1900.0,MRS.KARNJANA GOGERD,MRS.KARNJANA GOGERD,2026-06-05
19254,7211,2026-07-31,1557545,JE00774,CFN-15001,BRAKE,AAH-2;AAH-3 S/N:N44173 M16,2026-08-14,1581.0,2.0,3162.0,MS.KAMONRAT SORNPROM,MS.KAMONRAT SORNPROM,2026-07-31
19840,7211,2026-08-04,2009696,MM08218,Unknown,OIL SEAL,USH-095,2026-08-10,59.0,6.0,354.0,MS.PHUNCHALEE MEEPRADIT,MS.PHUNCHALEE MEEPRADIT,2026-08-04

In [65]:
# นับจำนวนข้อมูลที่ติดลบแยกตามรายคอลัมน์ และตรวจสอบผลลัพธ์
print((df[['UNIT_PRICE', 'ORDER_QTY', 'ORDER_AMT']] < 0).sum())
df.info()

UNIT_PRICE    0
ORDER_QTY     0
ORDER_AMT     0
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 22553 entries, 0 to 22552
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SECTION           22553 non-null  str
 1   SENT_DATE         22553 non-null  datetime64[us]
 2   VENDOR            22553 non-null  str
 3   PONO              22553 non-null  str
 4   ITEM_NO           22553 non-null  str
 5   ITEM_NAME         22553 non-null  str
 6   SPEC              22553 non-null  str
 7   DUEDATE           22553 non-null  datetime64[us]
 8   UNIT_PRICE        22553 non-null  float64
 9   ORDER_QTY         22553 non-null  float64
 10  ORDER_AMT         22553 non-null  float64
 11  BUYER_NAME        22553 non-null  str
 12  AUTHOLIZER_NAME   22553 non-null  str
 13  SENDING_DATETIME  22553 non-null  datetime64[us]
dtypes: datetime64[us](3), float64(3), str(8)
memory usage: 2.4 MB

In [66]:
# ลบแถวที่ PONO ขึ้นต้นด้วย STA หรือ DPB (เลือกเก็บเฉพาะแถวที่ไม่ใช่)
df = df[~df['PONO'].str.startswith(('STA'))]

In [67]:
#เพิ่มคอลัมน์แผนก

Department_Map = {'AA' : ' Assembly', 
                  'FA' : 'Asembly', 
                  'RG' : 'Rouge Grinding', 
                  'CF' : 'Cold Forming',
                  'TN' : 'Turning',
                  'HT' : 'Heat Treatment',
                  'BR' : 'Heat Treatment',
                  'MM' : 'Maintenance 41',
                  'FM' : 'Maintenance 41',
                  'MS' : 'Maintenance 40',
                  'MF' : 'Maintenance 40',
                  'QC' : 'Quility Control',
                  'QM' : 'Quility Control',
                  'EN' : 'Engineer',
                  'PC' : 'Production Control',
                  'QG' : 'Gauge Control',
                  'SG' : '2nd Grinding',
                  'FG' : '1st Grinding',
                  'FO' : '1st Grinding',
                  'FF' : '1st Grinding',
                  'TC' : 'Tooling Center',
                  'SS' : 'Store',
                  'PP' : 'PP',
                  'DP' : 'Despatch'}

df['Department'] = df['PONO'].str[:2].map(Department_Map)

df.info()
df.sample(5)

<class 'pandas.DataFrame'>
Index: 19787 entries, 4 to 22552
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SECTION           19787 non-null  str
 1   SENT_DATE         19787 non-null  datetime64[us]
 2   VENDOR            19787 non-null  str
 3   PONO              19787 non-null  str
 4   ITEM_NO           19787 non-null  str
 5   ITEM_NAME         19787 non-null  str
 6   SPEC              19787 non-null  str
 7   DUEDATE           19787 non-null  datetime64[us]
 8   UNIT_PRICE        19787 non-null  float64
 9   ORDER_QTY         19787 non-null  float64
 10  ORDER_AMT         19787 non-null  float64
 11  BUYER_NAME        19787 non-null  str
 12  AUTHOLIZER_NAME   19787 non-null  str
 13  SENDING_DATETIME  19787 non-null  datetime64[us]
 14  Department        19658 non-null  str
dtypes: datetime64[us](3), float64(3), str(9)
memory usage: 2.4 MB

,SECTION,SENT_DATE,VENDOR,PONO,ITEM_NO,ITEM_NAME,SPEC,DUEDATE,UNIT_PRICE,ORDER_QTY,ORDER_AMT,BUYER_NAME,AUTHOLIZER_NAME,SENDING_DATETIME,Department
2378,7211,2026-02-03,2007501,MSJ7026,NMN-25003,CAM SHAFT,PT37067-12-0130A,2026-03-12,2400.00,2.0,4800.00,MS.PHUNCHALEE MEEPRADIT,MS.PHUNCHALEE MEEPRADIT,2026-02-03,Maintenance 40
19414,7211,2026-08-01,2005607,MM08133,Unknown,BRACKETS,HBLFS6-SST,2026-09-01,37.87,16.0,605.92,MS.PHUNCHALEE MEEPRADIT,MS.PHUNCHALEE MEEPRADIT,2026-08-01,Maintenance 41
9362,7211,2026-04-22,2009626,MMF5234,Unknown,STEP DILL,CSD-1223TR (3PCS/SET),2026-05-05,6160.00,1.0,6160.00,MS.KAMONRAT SORNPROM,MS.PHUNCHALEE MEEPRADIT,2026-04-22,Maintenance 41
15136,7211,2026-06-16,2008375,TC32460,KA07701R,DRILL,SIZE:7.7 (COATING) 2-608 1680,2026-06-22,34.35,28.0,961.80,MS.PHUNCHALEE MEEPRADIT,MS.PHUNCHALEE MEEPRADIT,2026-06-16,Tooling Center
16315,7211,2026-07-01,2008860,MM07555,Unknown,ULTRASONIC TRANSDUCER BOX,ACE-1200B40 40 KHZ,2026-08-04,55000.00,1.0,55000.00,MS.KAMONRAT SORNPROM,MS.KAMONRAT SORNPROM,2026-07-01,Maintenance 41

In [68]:
#เติมช่องว่าง

df = df.dropna(subset=['Department'])
print(df.isnull().sum())

SECTION             0
SENT_DATE           0
VENDOR              0
PONO                0
ITEM_NO             0
ITEM_NAME           0
SPEC                0
DUEDATE             0
UNIT_PRICE          0
ORDER_QTY           0
ORDER_AMT           0
BUYER_NAME          0
AUTHOLIZER_NAME     0
SENDING_DATETIME    0
Department          0
dtype: int64

In [69]:
#ส่งออกไฟล์
df.to_csv('../Data/PO_Outgoing_List_Clean.csv', index=False)