In [8]:
import pandas as pd
import numpy as np

df = pd.read_csv("Monthly_Production.csv")
df.info()
df.sample(10)

<class 'pandas.DataFrame'>
RangeIndex: 16826 entries, 0 to 16825
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   YEAR4       16826 non-null  int64
 1   MONTH2      16826 non-null  int64
 2   PART_NO     16826 non-null  str
 3   RT          0 non-null      float64
 4   PROCESS     16826 non-null  str
 5   OK_QTY      16826 non-null  int64
 6   NG_QTY      16826 non-null  int64
 7   TYPE        16826 non-null  int64
 8   SPEC        0 non-null      float64
 9   SSPEC       0 non-null      float64
 10  PROCNAME    16826 non-null  str
 11  SERI        16826 non-null  str
 12  SIZE        16826 non-null  str
 13  AC_PROCESS  13764 non-null  float64
 14  GRP_PART    0 non-null      float64
dtypes: float64(5), int64(5), str(5)
memory usage: 1.9 MB

,YEAR4,MONTH2,PART_NO,RT,PROCESS,OK_QTY,NG_QTY,TYPE,SPEC,SSPEC,PROCNAME,SERI,SIZE,AC_PROCESS,GRP_PART
14375,2026,6,2-608X11SD101H05TP93(BIG),NaN,1201,216540,0,2,NaN,NaN,WASHING 1,2-608,SMALL,1120.0,NaN
13749,2026,6,1AS-1A32E01,NaN,1201,155265,0,1,NaN,NaN,WASHING 1,1-1A32,SMALL,1120.0,NaN
4494,2026,7,1SFLNR-1680XHHS2TP93,NaN,0740,383749,0,1,NaN,NaN,FACE GRINDING,1L-1680,SMALL,740.0,NaN
15083,2026,3,2SFR-1350X3ZZB56ATTP93(S),NaN,1201,178716,0,2,NaN,NaN,WASHING 1,2R-1350,SMALL,1120.0,NaN
3449,2026,6,1HCR-2210X3HH(SGC),NaN,0710,14181,0,1,NaN,NaN,HEAT TREATMENT,1R-2210,SMALL,710.0,NaN
12265,2026,1,1SF-626ZZATTP93,NaN,1120,265627,7379,1,NaN,NaN,S/F PROD.,1-626,SMALL,1120.0,NaN
10617,2026,7,2SF-626XZZ-NTP93,NaN,112R,25753,0,2,NaN,NaN,RE-SUPER FINISH,2-626,SMALL,1120.0,NaN
12051,2026,3,1HC-629X2ZZ,NaN,1120,320885,16786,1,NaN,NaN,S/F PROD.,1-629,MIDDLE,1120.0,NaN
15998,2026,7,2SF-608XZZ-N(SPC)(TB),NaN,1283,3240,0,2,NaN,NaN,RETURN FROM MATCHING,2-608,SMALL,1120.0,NaN
1103,2026,7,1SFR-1980HHSTP93,NaN,0260,3699543,10259,1,NaN,NaN,ROUGH GRINDING,1R-1980,SMALL,260.0,NaN

In [ ]:
#ลบคอลัมน์ที่มีแถวว่างทั้งหมด

df.isnull().sum()

df = df.dropna(axis=1, how="all")

In [ ]:
#เปลี่ยนชนิดข้อมูลเป็น string

df['AC_PROCESS'] = df['AC_PROCESS'].astype('str')

print(df.isnull().sum())
df.info()
display(df.sample(5))

YEAR4            0
MONTH2           0
PART_NO          0
PROCESS          0
OK_QTY           0
NG_QTY           0
TYPE             0
PROCNAME         0
SERI             0
SIZE             0
AC_PROCESS    3062
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 16826 entries, 0 to 16825
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   YEAR4       16826 non-null  int64
 1   MONTH2      16826 non-null  int64
 2   PART_NO     16826 non-null  str
 3   PROCESS     16826 non-null  str
 4   OK_QTY      16826 non-null  int64
 5   NG_QTY      16826 non-null  int64
 6   TYPE        16826 non-null  int64
 7   PROCNAME    16826 non-null  str
 8   SERI        16826 non-null  str
 9   SIZE        16826 non-null  str
 10  AC_PROCESS  13764 non-null  str
dtypes: int64(5), str(6)
memory usage: 1.4 MB

,YEAR4,MONTH2,PART_NO,PROCESS,OK_QTY,NG_QTY,TYPE,PROCNAME,SERI,SIZE,AC_PROCESS
7119,2026,3,1AS-1A06E01TP93,0948,63095,0,1,BARREL BEFORE RACE G.,1-608,SMALL,760.0
3199,2026,1,1SFL-2010ZZSD718S3TP93,071H,207213,0,1,A/F HEAT FROM NHT,1L-2010,SMALL,550.0
14940,2026,7,2SF-629X2ZZSD25S3-N,1201,142740,0,2,WASHING 1,2-629,MIDDLE,1120.0
3138,2026,2,2SFR-2210X3HHSD21-NTP93,07B1,375000,-2764,2,SIDE LAP (NO OD GRINDING),2R-2210,SMALL,760.0
9020,2026,4,2-608X11H05ATTP93(T),112M,12960,0,2,SUPER FINISH,2-608,SMALL,1120.0

In [ ]:
#เติมช่องว่างด้วย Unknown

str_columns = df.select_dtypes(include=['object']).columns

df[str_columns] = df[str_columns].fillna('Unknown')

print(df.isna().sum())
print(df.info())
df.sample(10)

YEAR4         0
MONTH2        0
PART_NO       0
PROCESS       0
OK_QTY        0
NG_QTY        0
TYPE          0
PROCNAME      0
SERI          0
SIZE          0
AC_PROCESS    0
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 16826 entries, 0 to 16825
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   YEAR4       16826 non-null  int64
 1   MONTH2      16826 non-null  int64
 2   PART_NO     16826 non-null  str
 3   PROCESS     16826 non-null  str
 4   OK_QTY      16826 non-null  int64
 5   NG_QTY      16826 non-null  int64
 6   TYPE        16826 non-null  int64
 7   PROCNAME    16826 non-null  str
 8   SERI        16826 non-null  str
 9   SIZE        16826 non-null  str
 10  AC_PROCESS  16826 non-null  str
dtypes: int64(5), str(6)
memory usage: 1.4 MB
None

C:\Users\bpt7474\AppData\Local\Temp\ipykernel_6760\3240939263.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  str_columns = df.select_dtypes(include=['object']).columns

,YEAR4,MONTH2,PART_NO,PROCESS,OK_QTY,NG_QTY,TYPE,PROCNAME,SERI,SIZE,AC_PROCESS
5648,2026,7,1SF-608X7ZZSD87S2TP93,0900,0,0,1,A/F PROCESS SEL,1-608,SMALL,Unknown
5451,2026,5,1SF-626ZZSD25TP93,09F7,174314,2800,1,R/W SORTING,1-626,SMALL,Unknown
5821,2026,3,2SF-6000X2ZZ-NTP93(D)SPC,0900,0,0,2,A/F PROCESS SEL,2-6000,MIDDLE,Unknown
14687,2026,7,2SF-608XZZSD87CV,1201,1620,0,2,WASHING 1,2-608,SMALL,1120.0
11136,2026,3,2R-2210X3B18SD21MT-NTP93,1120,28805,0,2,S/F PROD.,2R-2210,SMALL,1120.0
13799,2026,6,1HC-609ZZS3,1201,8866,0,1,WASHING 1,1-609,MIDDLE,1120.0
15506,2026,2,1SFL-2010ZZSD718MTS3TP93,1282,74943,0,1,UNMATCH FROM MATCHING,1L-2010,SMALL,1120.0
4868,2026,1,1SF-608ZZNRSD03S2TP93,0760,495206,0,1,O.D. GRINDING,1-608,SMALL,760.0
16195,2026,1,2SF-626XZZ-NTP93(SPC)(S),1283,1120,0,2,RETURN FROM MATCHING,2-626,SMALL,1120.0
206,2026,7,2SFL-2112HH,0110,480977,1180,2,TURNING I/R,2L-2112,SMALL,110.0

In [36]:
#เช็คคอลัมน์ที่มีตัวเลขติดลบ

number_df = df.select_dtypes(include=['number'])
column_negative = number_df.columns[(number_df < 0).any()].tolist()



print("คอลัมน์ที่มีข้อมูลติดลบ:", column_negative)
print((df['NG_QTY']<0).sum())
display(df.sample(10))

คอลัมน์ที่มีข้อมูลติดลบ: ['NG_QTY']
187

,YEAR4,MONTH2,PART_NO,PROCESS,OK_QTY,NG_QTY,TYPE,PROCNAME,SERI,SIZE,AC_PROCESS
3882,2026,5,2SFL-1680X2HH(T),0710,156088,0,2,HEAT TREATMENT,2L-1680,SMALL,710.0
2439,2026,6,1SF-626ZZ,0600,4746,0,1,INPROCESS SELECTION,1-626,SMALL,Unknown
670,2026,2,1SF-608ZZS2TP93,0210,29385200,293454,1,ROUGH SIDE LAP GRINDING1,1-608,SMALL,Unknown
8131,2026,6,2SF-608ZZSD21-N,1028,144001,0,2,BARREL BEFORE RACE GRD.,2-608,SMALL,760.0
14077,2026,3,1SFL-1680XHHCVS2TP93,1201,105607,0,1,WASHING 1,1L-1680,SMALL,1120.0
264,2026,6,2SFR-2210X6HH-NTP93(T),0110,1173,0,2,TURNING I/R,2R-2210,SMALL,110.0
3720,2026,4,2R-2210X3SD21-NTP93(T),0710,280948,12,2,HEAT TREATMENT,2R-2210,SMALL,710.0
6877,2026,2,1SF-608X7TP93(NOS)SPC,0940,1999671,0,1,RACE WAY GRINDING (O/R),1-608,SMALL,Unknown
15329,2026,2,1AS-1854E01,1282,8279,0,1,UNMATCH FROM MATCHING,1AS-1854,SMALL,1120.0
14615,2026,4,2SF-608XZZ-NTP93(SPC)(S),1201,1164120,0,2,WASHING 1,2-608,SMALL,1120.0

In [ ]:
#แปลงข้อมูลติดลบเป็นบวก

df['NG_QTY'] = df['NG_QTY'].abs()
print((df['NG_QTY']<0).sum())
display(df.sample(10))

0

,YEAR4,MONTH2,PART_NO,PROCESS,OK_QTY,NG_QTY,TYPE,PROCNAME,SERI,SIZE,AC_PROCESS
16089,2026,3,2SF-608X12ZZ-NTP93(T),1283,9651,0,2,RETURN FROM MATCHING,2-608,SMALL,1120.0
7392,2026,7,1SFR-1350X3ZZTP93,0948,1231103,0,1,BARREL BEFORE RACE G.,1R-1350,SMALL,760.0
12672,2026,2,1SF-608X6ZZNRTP93,120R,958,0,1,RE-WASHING,1-608,SMALL,1120.0
12901,2026,5,2-608X11SD101H05TP93(BIG),120R,160500,0,2,RE-WASHING,2-608,SMALL,1120.0
16588,2026,4,1SF-608ZZS2TP93,1284,141581,0,1,RETURN FROM REWORK,1-608,SMALL,1120.0
2833,2026,1,2SFR-2210X4HHTP93,0600,21026,0,2,INPROCESS SELECTION,2R-2210,SMALL,Unknown
11563,2026,5,2SF-626XZZB70-NTP93,1120,110530,3780,2,S/F PROD.,2-626,SMALL,1120.0
10554,2026,7,2SF-608ZZSD21-N(S),112R,54981,0,2,RE-SUPER FINISH,2-608,SMALL,1120.0
8647,2026,3,1R-1650X9HHSD273ATS2TP93,112M,882,0,1,SUPER FINISH,1R-1650,SMALL,1120.0
9370,2026,1,2SF-608XZZB55-NTP93(S),112M,3240,0,2,SUPER FINISH,2-608,SMALL,1120.0

In [ ]:
#ตรวจสอบข้อมูลก่อนส่งออก

print(df.info())
print(df.isnull().sum())
print(f"จำนวนแถวคงเหลือ: {len(df)}")

<class 'pandas.DataFrame'>
RangeIndex: 16826 entries, 0 to 16825
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   YEAR4       16826 non-null  int64
 1   MONTH2      16826 non-null  int64
 2   PART_NO     16826 non-null  str
 3   PROCESS     16826 non-null  str
 4   OK_QTY      16826 non-null  int64
 5   NG_QTY      16826 non-null  int64
 6   TYPE        16826 non-null  int64
 7   PROCNAME    16826 non-null  str
 8   SERI        16826 non-null  str
 9   SIZE        16826 non-null  str
 10  AC_PROCESS  16826 non-null  str
dtypes: int64(5), str(6)
memory usage: 1.4 MB
None
YEAR4         0
MONTH2        0
PART_NO       0
PROCESS       0
OK_QTY        0
NG_QTY        0
TYPE          0
PROCNAME      0
SERI          0
SIZE          0
AC_PROCESS    0
dtype: int64
จำนวนแถวคงเหลือ: 16826

In [48]:
df.to_csv("Monthly_Production_Clean.csv", index=False)