In [6]:
import pandas as pd

df = pd.read_csv('PO_Outgoing_List.csv')

print("\n ----------รายละเอียด----------")
print(df.info())
print("\n ----------จำนวนแถวและคอมลัมน์----------")
print(df.shape)
print("\n ----------จำนวนข้อมูลซ้ำ----------")
print(df.duplicated().sum())
print("\n ----------จำนวนข้อมูลว่าง----------")
print(df.isna().sum())
print("\n ----------ตัวอย่างข้อมูล----------")
display(df.sample(5))

 ----------รายละเอียด----------
<class 'pandas.DataFrame'>
RangeIndex: 22553 entries, 0 to 22552
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SECTION           22553 non-null  int64
 1   SENT_DATE         22553 non-null  str
 2   VENDOR            22553 non-null  int64
 3   PONO              22553 non-null  str
 4   ITEM_NO           10398 non-null  str
 5   ITEM_NAME         22553 non-null  str
 6   SPEC              22548 non-null  str
 7   DUEDATE           22553 non-null  str
 8   UNIT_PRICE        22553 non-null  float64
 9   ORDER_QTY         22553 non-null  float64
 10  ORDER_AMT         22553 non-null  float64
 11  BUYER_NAME        22553 non-null  str
 12  AUTHOLIZER_NAME   22553 non-null  str
 13  SENDING_DATETIME  22553 non-null  str
 14  Unnamed: 14       0 non-null      float64
dtypes: float64(4), int64(2), str(9)
memory usage: 2.6 MB
None

 ----------จำนวนแถวและคอมลัมน์----------
(22553, 15)

 ----------จำนวนข้อมูลซ้ำ----------
0

 ----------จำนวนข้อมูลว่าง----------
SECTION                 0
SENT_DATE               0
VENDOR                  0
PONO                    0
ITEM_NO             12155
ITEM_NAME               0
SPEC                    5
DUEDATE                 0
UNIT_PRICE              0
ORDER_QTY               0
ORDER_AMT               0
BUYER_NAME              0
AUTHOLIZER_NAME         0
SENDING_DATETIME        0
Unnamed: 14         22553
dtype: int64

 ----------ตัวอย่างข้อมูล----------

,SECTION,SENT_DATE,VENDOR,PONO,ITEM_NO,ITEM_NAME,SPEC,DUEDATE,UNIT_PRICE,ORDER_QTY,ORDER_AMT,BUYER_NAME,AUTHOLIZER_NAME,SENDING_DATETIME,Unnamed: 14
8452,7211,2026/04/09,2061231,TN05405,NaN,SAFTY CAM,37071-06-0520,2026-04-06,1860.0,2.0,3720.0,MRS.KARNJANA GOGERD,MRS.KARNJANA GOGERD,2026-04-09-16.16.13,NaN
18943,7211,2026/07/24,2000377,CFL0694,NaN,FORK WHEEL FOR BDH,BSI17-76027275,2026-08-05,1200.0,2.0,2400.0,MS.KAMONRAT SORNPROM,MS.PHUNCHALEE MEEPRADIT,2026-07-24-17.34.06,NaN
15441,7211,2026/06/19,2009696,MF51956,CFN-12001,BRAKE,DIA98X19TMM(BROWN)/SF,2026-07-20,2006.0,4.0,8024.0,MS.PHUNCHALEE MEEPRADIT,MS.PHUNCHALEE MEEPRADIT,2026-06-19-16.50.28,NaN
7634,7211,2026/03/27,2160615,TN05601,NaN,JAW SENSOR POS.4 UNIT,PT30007-18-T1548,2026-05-05,940.0,2.0,1880.0,MRS.KARNJANA GOGERD,MRS.KARNJANA GOGERD,2026-03-27-11.42.55,NaN
20836,7211,2026/08/14,2009696,MM08511,NaN,DC GEAR MOTOR,ZGA25RP 30RPM 24VDC,2026-09-03,450.0,44.0,19800.0,MS.PHUNCHALEE MEEPRADIT,MS.PHUNCHALEE MEEPRADIT,2026-08-14-07.25.25,NaN

In [7]:
#แปลงชนิดข้อมูลคอมลัมน์ SECTION และ VENDOR เป็น string

df = df.astype({'SECTION':'str','VENDOR':'str'})
print("\n -----------รายละเอียด-----------")
print(df.info())

 -----------รายละเอียด-----------
<class 'pandas.DataFrame'>
RangeIndex: 22553 entries, 0 to 22552
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SECTION           22553 non-null  str
 1   SENT_DATE         22553 non-null  str
 2   VENDOR            22553 non-null  str
 3   PONO              22553 non-null  str
 4   ITEM_NO           10398 non-null  str
 5   ITEM_NAME         22553 non-null  str
 6   SPEC              22548 non-null  str
 7   DUEDATE           22553 non-null  str
 8   UNIT_PRICE        22553 non-null  float64
 9   ORDER_QTY         22553 non-null  float64
 10  ORDER_AMT         22553 non-null  float64
 11  BUYER_NAME        22553 non-null  str
 12  AUTHOLIZER_NAME   22553 non-null  str
 13  SENDING_DATETIME  22553 non-null  str
 14  Unnamed: 14       0 non-null      float64
dtypes: float64(4), str(11)
memory usage: 2.6 MB
None

In [8]:
#แปลงชนิดข้อมูลวันที่
df['SENT_DATE'] = pd.to_datetime(df['SENT_DATE'],errors='coerce')
df['DUEDATE'] = pd.to_datetime(df['DUEDATE'],errors='coerce')
df['SENDING_DATETIME'] = df['SENDING_DATETIME'].astype('str').str[:10]
df['SENDING_DATETIME'] = pd.to_datetime(df['SENDING_DATETIME'],errors='coerce')

print("\n ตรวจสอบข้อมูล")
print(df.info())
print('\n ตัวอย่างข้อมูล')
display(df.sample(5))

 ตรวจสอบข้อมูล
<class 'pandas.DataFrame'>
RangeIndex: 22553 entries, 0 to 22552
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SECTION           22553 non-null  str
 1   SENT_DATE         22553 non-null  datetime64[us]
 2   VENDOR            22553 non-null  str
 3   PONO              22553 non-null  str
 4   ITEM_NO           10398 non-null  str
 5   ITEM_NAME         22553 non-null  str
 6   SPEC              22548 non-null  str
 7   DUEDATE           22553 non-null  datetime64[us]
 8   UNIT_PRICE        22553 non-null  float64
 9   ORDER_QTY         22553 non-null  float64
 10  ORDER_AMT         22553 non-null  float64
 11  BUYER_NAME        22553 non-null  str
 12  AUTHOLIZER_NAME   22553 non-null  str
 13  SENDING_DATETIME  22553 non-null  datetime64[us]
 14  Unnamed: 14       0 non-null      float64
dtypes: datetime64[us](3), float64(4), str(8)
memory usage: 2.6 MB
None

 ตัวอย่างข้อมูล

,SECTION,SENT_DATE,VENDOR,PONO,ITEM_NO,ITEM_NAME,SPEC,DUEDATE,UNIT_PRICE,ORDER_QTY,ORDER_AMT,BUYER_NAME,AUTHOLIZER_NAME,SENDING_DATETIME,Unnamed: 14
15708,7211,2026-06-24,2000670,STA9163,NE00063A,PLASTIC BAG,"15""X24""X0.05 MM",2026-06-29,92.00,200.0,18400.00,MS.ROANGTHONG MOMMOUETHONG,MS.ROANGTHONG MOMMOUETHONG,2026-06-24,NaN
10297,7211,2026-04-28,2002207,MSJ7719,SWN-01032,CAP SCREW,M8X20,2026-05-11,2.08,200.0,416.00,MS.PHUNCHALEE MEEPRADIT,MS.PHUNCHALEE MEEPRADIT,2026-04-28,NaN
20206,7211,2026-08-06,2060294,TN05825,NaN,LOCKING ARM HOLDER 4 DEGREE,PT37071-12-0040A,2026-08-06,1800.00,5.0,9000.00,MRS.KARNJANA GOGERD,MRS.KARNJANA GOGERD,2026-08-06,NaN
7155,7211,2026-03-25,2005607,ENQ4014,NaN,URETHANE SHEET,UTSLL2H10-298-44-F170-G22-Z4,2026-04-03,614.04,1.0,614.04,MS.KAMONRAT SORNPROM,MS.PHUNCHALEE MEEPRADIT,2026-03-25,NaN
14673,7211,2026-06-10,2009592,ENQ7701,NaN,FILAMENT,PLA+ 1.75MM 1KG WHITE,2026-06-16,710.00,5.0,3550.00,MS.KAMONRAT SORNPROM,MS.KAMONRAT SORNPROM,2026-06-10,NaN

In [9]:
#ลบคอลัมน์ที่ไม่มีข้อิมูลเลย เติมข้อมูลในแถวว่าง
df = df.dropna(axis=1, how='all')
df = df.fillna({'ITEM_NO':'Unknown', 'SPEC':'Unknown'})

print('\nจำนวนข้อมูลว่าง')
print(df.isna().sum())
display(df.sample(5))

จำนวนข้อมูลว่าง
SECTION             0
SENT_DATE           0
VENDOR              0
PONO                0
ITEM_NO             0
ITEM_NAME           0
SPEC                0
DUEDATE             0
UNIT_PRICE          0
ORDER_QTY           0
ORDER_AMT           0
BUYER_NAME          0
AUTHOLIZER_NAME     0
SENDING_DATETIME    0
dtype: int64

,SECTION,SENT_DATE,VENDOR,PONO,ITEM_NO,ITEM_NAME,SPEC,DUEDATE,UNIT_PRICE,ORDER_QTY,ORDER_AMT,BUYER_NAME,AUTHOLIZER_NAME,SENDING_DATETIME
13336,7211,2026-06-04,2060294,FM61065,Unknown,ADJUST PLATE HOLDER,PT47064-53-T6925A,2026-07-15,600.0,20.0,12000.0,MS.PHUNCHALEE MEEPRADIT,MS.PHUNCHALEE MEEPRADIT,2026-06-04
16232,7211,2026-06-30,2008467,MM06383,Unknown,JOINT BRACKET,PT47064-30-T6461A,2026-07-01,520.0,1.0,520.0,MRS.KARNJANA GOGERD,MRS.KARNJANA GOGERD,2026-06-30
13737,7211,2026-06-05,2660073,MM06163,Unknown,SHAFT HOLDER,M47577-31-2211,2026-06-09,200.0,4.0,800.0,MRS.KARNJANA GOGERD,MRS.KARNJANA GOGERD,2026-06-05
13410,7211,2026-06-04,2008467,MM06571,Unknown,FIX PLATE 3,47577-52-0204,2026-06-19,675.0,1.0,675.0,MRS.KARNJANA GOGERD,MRS.KARNJANA GOGERD,2026-06-04
10646,7211,2026-05-04,2000325,MMF5330,Unknown,STUD,AS-5AB,2026-06-08,172.0,20.0,3440.0,MS.KAMONRAT SORNPROM,MS.PHUNCHALEE MEEPRADIT,2026-05-04

In [10]:
# นับจำนวนข้อมูลที่ติดลบแยกตามรายคอลัมน์ และตรวจสอบผลลัพธ์
print((df[['UNIT_PRICE', 'ORDER_QTY', 'ORDER_AMT']] < 0).sum())
df.info()

UNIT_PRICE    0
ORDER_QTY     0
ORDER_AMT     0
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 22553 entries, 0 to 22552
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SECTION           22553 non-null  str
 1   SENT_DATE         22553 non-null  datetime64[us]
 2   VENDOR            22553 non-null  str
 3   PONO              22553 non-null  str
 4   ITEM_NO           22553 non-null  str
 5   ITEM_NAME         22553 non-null  str
 6   SPEC              22553 non-null  str
 7   DUEDATE           22553 non-null  datetime64[us]
 8   UNIT_PRICE        22553 non-null  float64
 9   ORDER_QTY         22553 non-null  float64
 10  ORDER_AMT         22553 non-null  float64
 11  BUYER_NAME        22553 non-null  str
 12  AUTHOLIZER_NAME   22553 non-null  str
 13  SENDING_DATETIME  22553 non-null  datetime64[us]
dtypes: datetime64[us](3), float64(3), str(8)
memory usage: 2.4 MB

In [11]:
# ลบแถวที่ PONO ขึ้นต้นด้วย STA หรือ DPB (เลือกเก็บเฉพาะแถวที่ไม่ใช่)
df = df[~df['PONO'].str.startswith(('STA'))]

In [12]:
#เพิ่มคอลัมน์แผนก

Department_Map = {'AA' : ' Assembly', 
                  'FA' : 'Asembly', 
                  'RG' : 'Rouge Grinding', 
                  'CF' : 'Cold Forming',
                  'TN' : 'Turning',
                  'HT' : 'Heat Treatment',
                  'BR' : 'Heat Treatment',
                  'MM' : 'Maintenance 41',
                  'FM' : 'Maintenance 41',
                  'MS' : 'Maintenance 40',
                  'MF' : 'Maintenance 40',
                  'QC' : 'Quility Control',
                  'QM' : 'Quility Control',
                  'EN' : 'Engineer',
                  'PC' : 'Production Control',
                  'QG' : 'Gauge Control',
                  'SG' : '2nd Grinding',
                  'FG' : '1st Grinding',
                  'FO' : '1st Grinding',
                  'FF' : '1st Grinding',
                  'TC' : 'Tooling Center',
                  'SS' : 'Store',
                  'PP' : 'PP',
                  'DP' : 'Despatch'}

df['Department'] = df['PONO'].str[:2].map(Department_Map)

df.info()
df.sample(5)

<class 'pandas.DataFrame'>
Index: 19787 entries, 4 to 22552
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SECTION           19787 non-null  str
 1   SENT_DATE         19787 non-null  datetime64[us]
 2   VENDOR            19787 non-null  str
 3   PONO              19787 non-null  str
 4   ITEM_NO           19787 non-null  str
 5   ITEM_NAME         19787 non-null  str
 6   SPEC              19787 non-null  str
 7   DUEDATE           19787 non-null  datetime64[us]
 8   UNIT_PRICE        19787 non-null  float64
 9   ORDER_QTY         19787 non-null  float64
 10  ORDER_AMT         19787 non-null  float64
 11  BUYER_NAME        19787 non-null  str
 12  AUTHOLIZER_NAME   19787 non-null  str
 13  SENDING_DATETIME  19787 non-null  datetime64[us]
 14  Department        19658 non-null  str
dtypes: datetime64[us](3), float64(3), str(9)
memory usage: 2.4 MB

,SECTION,SENT_DATE,VENDOR,PONO,ITEM_NO,ITEM_NAME,SPEC,DUEDATE,UNIT_PRICE,ORDER_QTY,ORDER_AMT,BUYER_NAME,AUTHOLIZER_NAME,SENDING_DATETIME,Department
5132,7211,2026-03-06,2060294,FO10119,Unknown,STONE BASE,37419-02-2035C,2026-04-02,1200.00,1.0,1200.0,MRS.KARNJANA GOGERD,MS.PHUNCHALEE MEEPRADIT,2026-03-06,1st Grinding
19469,7211,2026-08-01,2005607,MM08197,Unknown,INSERTION NUT,HNTTSN6-6,2026-09-01,7.29,70.0,510.3,MS.PHUNCHALEE MEEPRADIT,MS.PHUNCHALEE MEEPRADIT,2026-08-01,Maintenance 41
12772,7211,2026-05-25,2160615,AA06265,Unknown,REWORK TABLE,420X580X600MM (QT.4847/2568),2026-07-03,5500.00,4.0,22000.0,MS.PHUNCHALEE MEEPRADIT,MS.PHUNCHALEE MEEPRADIT,2026-05-25,Assembly
8638,7211,2026-04-10,2008389,AA05013,Unknown,SLIDE CHUTE SIDE PLATE,PT47P04-01-0450,2026-06-10,300.00,2.0,600.0,MS.PHUNCHALEE MEEPRADIT,MS.PHUNCHALEE MEEPRADIT,2026-04-10,Assembly
22003,7211,2026-08-20,2104172,FA60605,Unknown,SPACER,PT47056-05-T6580A (MAT'L A6061),2026-09-11,1250.00,6.0,7500.0,MS.PHUNCHALEE MEEPRADIT,MS.PHUNCHALEE MEEPRADIT,2026-08-20,Asembly

In [13]:
#เติมช่องว่าง

df = df.dropna(subset=['Department'])
print(df.isnull().sum())

SECTION             0
SENT_DATE           0
VENDOR              0
PONO                0
ITEM_NO             0
ITEM_NAME           0
SPEC                0
DUEDATE             0
UNIT_PRICE          0
ORDER_QTY           0
ORDER_AMT           0
BUYER_NAME          0
AUTHOLIZER_NAME     0
SENDING_DATETIME    0
Department          0
dtype: int64

In [19]:
#Insert Lead time column
df['Lead_time'] = (df['DUEDATE'] - df['SENT_DATE']).dt.days
print(df.columns.tolist())
print(df.info())

['SECTION', 'SENT_DATE', 'VENDOR', 'PONO', 'ITEM_NO', 'ITEM_NAME', 'SPEC', 'DUEDATE', 'UNIT_PRICE', 'ORDER_QTY', 'ORDER_AMT', 'BUYER_NAME', 'AUTHOLIZER_NAME', 'SENDING_DATETIME', 'Department', 'Lead_time']
<class 'pandas.DataFrame'>
Index: 19658 entries, 4 to 22552
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SECTION           19658 non-null  str
 1   SENT_DATE         19658 non-null  datetime64[us]
 2   VENDOR            19658 non-null  str
 3   PONO              19658 non-null  str
 4   ITEM_NO           19658 non-null  str
 5   ITEM_NAME         19658 non-null  str
 6   SPEC              19658 non-null  str
 7   DUEDATE           19658 non-null  datetime64[us]
 8   UNIT_PRICE        19658 non-null  float64
 9   ORDER_QTY         19658 non-null  float64
 10  ORDER_AMT         19658 non-null  float64
 11  BUYER_NAME        19658 non-null  str
 12  AUTHOLIZER_NAME   19658 non-null  str
 13  SENDING_DATETIME  19658 non-null  datetime64[us]
 14  Department        19658 non-null  str
 15  Lead_time         19658 non-null  int64
dtypes: datetime64[us](3), float64(3), int64(1), str(9)
memory usage: 2.5 MB
None

In [16]:
#ส่งออกไฟล์
df.to_csv('PO_Outgoing_List_Clean.csv', index=False)