In [138]:
import pandas as pd

df = pd.read_csv('dirty_cafe_sales.csv')

In [139]:
# Check Data
print("\nDataFrame Info:")
print(df.info())
print("\nUnique Values:")
print(df.nunique())
print("\nFirst 10 Rows:")
display(df.head(10))

DataFrame Info:
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB
None

Unique Values:
Transaction ID      10000
Item                   10
Quantity                7
Price Per Unit          8
Total Spent            19
Payment Method          5
Location                4
Transaction Date      367
dtype: int64

First 10 Rows:

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

In [140]:
#Manage Head Column
df.columns = df.columns.str.strip().str.lower().str.replace(' ','_')
print(df.columns)

Index(['transaction_id', 'item', 'quantity', 'price_per_unit', 'total_spent',
       'payment_method', 'location', 'transaction_date'],
      dtype='str')

In [141]:
#Check for Duplicates
print(df.duplicated().sum())
display(df[df.duplicated()])

0

Empty DataFrame
Columns: [transaction_id, item, quantity, price_per_unit, total_spent, payment_method, location, transaction_date]
Index: []

In [142]:
#Change Data Type


df['transaction_date'] = pd.to_datetime(df['transaction_date'], format='%Y-%m-%d', errors='coerce')
df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')
df['price_per_unit'] = pd.to_numeric(df['price_per_unit'], errors='coerce')
df['total_spent'] = pd.to_numeric(df['total_spent'], errors='coerce')

print(df.info())
display(df.head(10))

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  str
 1   item              9667 non-null   str
 2   quantity          9521 non-null   float64
 3   price_per_unit    9467 non-null   float64
 4   total_spent       9498 non-null   float64
 5   payment_method    7421 non-null   str
 6   location          6735 non-null   str
 7   transaction_date  9540 non-null   datetime64[us]
dtypes: datetime64[us](1), float64(3), str(4)
memory usage: 625.1 KB
None

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3.0,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5.0,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,2023-12-31

In [143]:
#Check for Missing Values
print(df.isna().sum())

df['item'] = df['item'].fillna('Unknown')
df['quantity'] = df['quantity'].fillna(df['quantity'].median())
df['price_per_unit'] = df.groupby('item')['price_per_unit'].transform(lambda x: x.ffill().bfill())
df['total_spent'] = df['total_spent'].fillna(df['quantity'] * df['price_per_unit'])
df['payment_method'] = df['payment_method'].fillna('Unknown')
df['location'] = df['location'].replace(['ERROR','UNKNOWN'],'Other').fillna('Other')
df['transaction_date'] = df['transaction_date'].fillna('Unknown')

print('\nData After Fill Na')
print(df.isna().sum())
display(df.sample(10))

transaction_id         0
item                 333
quantity             479
price_per_unit       533
total_spent          502
payment_method      2579
location            3265
transaction_date     460
dtype: int64

Data After Fill Na
transaction_id      0
item                0
quantity            0
price_per_unit      0
total_spent         0
payment_method      0
location            0
transaction_date    0
dtype: int64

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
4877,TXN_9468033,Juice,1.0,3.0,3.0,Credit Card,Other,2023-12-13 00:00:00
432,TXN_7555408,Salad,2.0,5.0,10.0,UNKNOWN,In-store,2023-06-06 00:00:00
3940,TXN_7469391,Coffee,5.0,2.0,10.0,Cash,In-store,Unknown
1129,TXN_1568657,Coffee,2.0,2.0,4.0,Cash,Other,Unknown
6130,TXN_3865627,Coffee,4.0,2.0,8.0,Unknown,In-store,2023-02-16 00:00:00
1657,TXN_7730388,Cookie,5.0,1.0,5.0,Digital Wallet,In-store,2023-09-09 00:00:00
9118,TXN_8365857,Smoothie,5.0,4.0,20.0,Digital Wallet,Takeaway,2023-10-06 00:00:00
7839,TXN_3635628,Sandwich,3.0,4.0,12.0,Digital Wallet,In-store,2023-10-28 00:00:00
5572,TXN_1643870,Salad,4.0,5.0,20.0,Digital Wallet,Takeaway,2023-10-07 00:00:00
3062,TXN_4847617,Sandwich,4.0,4.0,16.0,Credit Card,Other,2023-08-04 00:00:00

In [144]:
#Manage Unknown Value
import numpy as np

df['item'] = df['item'].replace(['UNKNOWN','ERROR'],'Unknown')
df['payment_method'] = df['payment_method'].replace(['UNKNOWN','ERROR'] , 'Unknown')
df['transaction_date'] = df['transaction_date'].replace('UNKNOWN' , np.nan).ffill()

display(df.sample(10))

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
2143,TXN_9126502,Smoothie,5.0,4.0,20.0,Credit Card,Other,2023-09-22 00:00:00
3942,TXN_1489746,Cookie,3.0,1.0,3.0,Digital Wallet,In-store,2023-12-18 00:00:00
6134,TXN_6335909,Salad,4.0,5.0,20.0,Unknown,In-store,2023-06-21 00:00:00
9614,TXN_2875074,Cake,4.0,3.0,12.0,Credit Card,Takeaway,2023-02-06 00:00:00
2094,TXN_2694724,Sandwich,2.0,4.0,8.0,Digital Wallet,Other,2023-06-26 00:00:00
7708,TXN_3454881,Salad,1.0,5.0,5.0,Cash,In-store,2023-11-29 00:00:00
2485,TXN_5403707,Smoothie,3.0,4.0,12.0,Cash,In-store,2023-03-20 00:00:00
7321,TXN_4163126,Sandwich,3.0,4.0,12.0,Digital Wallet,Takeaway,Unknown
9919,TXN_6706599,Cake,1.0,3.0,3.0,Unknown,Takeaway,2023-09-20 00:00:00
9504,TXN_8532735,Coffee,2.0,2.0,4.0,Cash,Takeaway,2023-07-28 00:00:00

In [145]:
# Check Dataframe
print('\n---------------- Data Frame Information--------------------')
print(df.info())
print('\n----------------Missing Value--------------------------')
print(df.isna().sum())
print('\n-----------------Unique Value------------------------')
print(df.nunique())
print('\n-----------------Sample Value------------------------')
display(df.sample(5))

---------------- Data Frame Information--------------------
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  str
 1   item              10000 non-null  str
 2   quantity          10000 non-null  float64
 3   price_per_unit    10000 non-null  float64
 4   total_spent       10000 non-null  float64
 5   payment_method    10000 non-null  str
 6   location          10000 non-null  str
 7   transaction_date  10000 non-null  object
dtypes: float64(3), object(1), str(4)
memory usage: 625.1+ KB
None

----------------Missing Value--------------------------
transaction_id      0
item                0
quantity            0
price_per_unit      0
total_spent         0
payment_method      0
location            0
transaction_date    0
dtype: int64

-----------------Unique Value------------------------

transaction_id      10000
item                    9
quantity                5
price_per_unit          6
total_spent            17
payment_method          4
location                3
transaction_date      366
dtype: int64

-----------------Sample Value------------------------

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
8223,TXN_6624397,Juice,4.0,3.0,12.0,Cash,Takeaway,2023-04-30 00:00:00
9954,TXN_1191659,Coffee,4.0,2.0,8.0,Credit Card,In-store,2023-11-21 00:00:00
9708,TXN_6895558,Coffee,2.0,2.0,4.0,Credit Card,Other,2023-04-10 00:00:00
2100,TXN_5956755,Sandwich,5.0,4.0,20.0,Digital Wallet,Takeaway,2023-03-05 00:00:00
4112,TXN_6045577,Unknown,3.0,2.0,6.0,Credit Card,Other,2023-07-06 00:00:00

In [146]:
df['transaction_date'] = pd.to_datetime(df['transaction_date'], errors='coerce')
df['transaction_date'] = df['transaction_date'].fillna(df['transaction_date'].ffill())
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    10000 non-null  str
 1   item              10000 non-null  str
 2   quantity          10000 non-null  float64
 3   price_per_unit    10000 non-null  float64
 4   total_spent       10000 non-null  float64
 5   payment_method    10000 non-null  str
 6   location          10000 non-null  str
 7   transaction_date  10000 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(3), str(4)
memory usage: 625.1 KB
None

In [147]:
# ดูจำนวนแถวทั้งหมดที่เป็น 'ERROR'
print((df['item'] == 'ERROR').sum())
print((df['payment_method'] == 'ERROR').sum())

# หรือกรณีที่มีคำว่า 'ERROR' ปนอยู่กับข้อความอื่น (เช่น 'ERROR_404', 'SYSTEM ERROR')
error_rows = df[df['item'].astype(str).str.contains('ERROR', case=False, na=False)]

0
0

In [148]:
df.to_csv('cleaned_cafe_sales.csv', index=False)